name: publish

on:
  push:
    paths:
      - "enterprise/**"
    branches: [ dev ]

jobs: 
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/enterprise-api:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/enterprise-api:latest

      - name: Deploy
        run: |
          gcloud run deploy \
          --region us-east4-a \
          --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/enterprise-api \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCLOUD_PROJECT_ID }}
